server:
  port: 8765


spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: cart-service
          uri: http://localhost:8081/
          predicates:
            - Path=/cart/**
        - id: product-service
          uri: http://localhost:8082/
          predicates:
            - Path=/products/**


